routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::redirect('/', '/login');
Route::redirect('/register', '/login');
Route::redirect('/password/reset', '/login');

Route::group(['middleware' => ['auth']], function () {
    Route::get('/package/select', 'PackageController@select')->name('package.select');
    Route::resource('/package', 'PackageController');
    Route::resource('/mosque', 'MosqueController');
    Route::get('/province/select', 'ProvinceController@select')->name('province.select');
    Route::put('/mosque/{mosque}', 'MosqueController@updateacp')->name('mosque.updateacp');
    Route::post('/mosque/renew-subscribe/{mosque}', 'MosqueController@renewsubscribe')->name('mosque.renewsubscribe');
    Route::resource('/bank', 'BankController');
    Route::get('/team/select', 'TeamController@select')->name('team.select');
    Route::resource('/team', 'TeamController');
    Route::post('/withdraw/accept/{withdraw}', 'TeamWithdrawController@accept')->name('team.accept');
    Route::post('/withdraw/decline/{withdraw}', 'TeamWithdrawController@decline')->name('team.decline');
    Route::resource('withdraw', 'TeamWithdrawController')->only([
      'index', 'delete'
    ]);
});

Route::get('/{vue_capture?}', function () {
    return view('layouts.app');
})->where('vue_capture', '[\/\w\.-]*');

resources/views/bank-form.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="card card-primary card-outline">
          <div class="card-header">
          </div><!-- /.card-header -->
          <div class="card-body">
              @if (isset($bank))
                  <form method="POST" action="{{ route('bank.update', $bank->id) }}">
                    @csrf
                    @method('PUT')
                    <div class="form-group row">
                      <label for="name" class="col-sm-4 col-form-label">Nama Bank</label>
                      <div class="col-sm-8">
                        <input type="text" class="form-control" name="name" id="name" placeholder="Nama Bank" value="{{ $bank->name }}" required>
                      </div>
                    </div>
                    <div class="form-group row">
                      <div class="col-sm-12 text-right">
                          <a href="{{ route('bank.index') }}" class="btn btn-secondary">
                              Batal
                          </a>
                          <button type="submit" class="btn btn-primary">Simpan</button>
                      </div>
                    </div>
                  </form>
              @else
                  <form method="POST" action="{{ route('bank.store') }}">
                    @csrf
                    @method('POST')
                    <div class="form-group row">
                      <label for="name" class="col-sm-4 col-form-label">Nama Bank</label>
                      <div class="col-sm-8">
                        <input type="text" class="form-control" name="name" id="name" placeholder="Nama Bank" required>
                      </div>
                    </div>
                    <div class="form-group row">
                      <div class="col-sm-12 text-right">
                          <a href="{{ route('bank.index') }}" class="btn btn-secondary">
                              Batal
                          </a>
                          <button type="submit" class="btn btn-primary">Simpan</button>
                      </div>
                    </div>
                  </form>
              @endif
          </div><!-- /.card-body -->
        </div>
        <!-- /.nav-tabs-custom -->
      </div>
      <!-- /.col -->
    </div>
</div>

<script type="text/javascript">
</script>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/mosque-form.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="card card-primary card-outline">
          <div class="card-header">
          </div><!-- /.card-header -->
          <div class="card-body">
              @if (isset($mosque))
                  <form method="POST" action="{{ route('mosque.updateacp', $mosque->id) }}">
                    @csrf
                    @method('PUT')
                    <div class="form-group row">
                      <label for="number" class="col-sm-2 col-form-label">Nomor</label>
                      <div class="col-sm-10">
                        <input type="text" class="form-control" name="number" id="number" placeholder="Nomor" value="{{ $mosque->number }}" required readonly>
                      </div>
                    </div>
                    <div class="form-group row">
                      <label for="name" class="col-sm-2 col-form-label">Nama Masjid</label>
                      <div class="col-sm-10">
                        <input type="text" class="form-control" name="name" id="name" placeholder="Nama Masjid" value="{{ $mosque->name }}" required>
                      </div>
                    </div>
                    <div class="form-group row">
                        <label for="address" class="col-sm-2 col-form-label">Alamat</label>
                        <div class="col-sm-10">
                            <textarea class="form-control" name="address" id="address" rows="3" placeholder="Alamat" required>{{ $mosque->address }}</textarea>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="province" class="col-sm-2 col-form-label">Provinsi</label>
                        <div class="col-sm-10">
                            <input type="hidden" id="province_real" value="{{ $mosque->province_id }}">
                            <select class="form-control" name="province" id="province" required>
                            </select>
                        </div>
                    </div>
                    <div class="form-group row">
                      <label for="takmir_name" class="col-sm-2 col-form-label">Nama Takmir</label>
                      <div class="col-sm-10">
                        <input type="hidden" name="takmir_id" value="{{ $mosque->takmir[0]->id }}" readonly>
                        <input type="text" class="form-control" name="takmir_name" id="takmir_name" placeholder="Nama Takmir" value="{{ $mosque->takmir[0]->name }}" required>
                      </div>
                    </div>
                    <div class="form-group row">
                      <label for="username" class="col-sm-2 col-form-label">Username</label>
                      <div class="col-sm-10">
                        <input type="text" class="form-control" name="username" id="username" placeholder="Username" value="{{ $mosque->takmir[0]->username }}" required readonly>
                      </div>
                    </div>
                    <div class="form-group row">
                      <label for="password" class="col-sm-2 col-form-label">Password</label>
                      <div class="col-sm-10">
                        <input type="password" class="form-control" name="password" id="password" placeholder="Password">
                        <small class="form-text text-muted">
                            Kosongkan jika tidak diganti.
                        </small>
                      </div>
                    </div>
                    <div class="form-group row">
                        <label for="package_id" class="col-sm-2 col-form-label">Jenis Paket</label>
                        <div class="col-sm-10">
                            <input type="hidden" id="package_id_real" value="{{ $mosque->package_id }}">
                            <select class="form-control" name="package_id" id="package_id" required>
                            </select>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="team_id" class="col-sm-2 col-form-label">Sahabat</label>
                        <div class="col-sm-10">
                            <input type="hidden" id="team_id_real" value="{{ $mosque->team_id }}">
                            <select class="form-control" name="team_id" id="team_id" required>
                            </select>
                        </div>
                    </div>
                    <!-- <div class="form-group row">
                        <label for="last_subscribe" class="col-sm-2 col-form-label">Tanggal Terakhir Berlangganan</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control datepicker" name="last_subscribe" id="last_subscribe" placeholder="Tanggal Terakhir Berlangganan" value="{{ date('m/d/Y', strtotime($mosque->last_subscribe)) }}" required>
                        </div>
                    </div> -->
                    <div class="form-group row">
                      <div class="col-sm-12 text-right">
                          <a href="{{ route('mosque.index') }}" class="btn btn-secondary">
                              Batal
                          </a>
                          <button type="submit" class="btn btn-primary">Simpan</button>
                      </div>
                    </div>
                  </form>
              @else
                  <form method="POST" action="{{ route('mosque.store') }}">
                    @csrf
                    @method('POST')
                    <div class="form-group row">
                      <label for="name" class="col-sm-2 col-form-label">Nama Masjid</label>
                      <div class="col-sm-10">
                        <input type="text" class="form-control" name="name" id="name" placeholder="Nama Masjid" required>
                      </div>
                    </div>
                    <div class="form-group row">
                        <label for="address" class="col-sm-2 col-form-label">Alamat</label>
                        <div class="col-sm-10">
                            <textarea class="form-control" name="address" id="address" rows="3" placeholder="Alamat" required></textarea>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="province" class="col-sm-2 col-form-label">Provinsi</label>
                        <div class="col-sm-10">
                            <select class="form-control" name="province" id="province" required>
                            </select>
                        </div>
                    </div>
                    <div class="form-group row">
                      <label for="takmir_name" class="col-sm-2 col-form-label">Nama Takmir</label>
                      <div class="col-sm-10">
                        <input type="text" class="form-control" name="takmir_name" id="takmir_name" placeholder="Nama Takmir" required>
                      </div>
                    </div>
                    <div class="form-group row">
                      <label for="username" class="col-sm-2 col-form-label">Username</label>
                      <div class="col-sm-10">
                        <input type="text" class="form-control" name="username" id="username" placeholder="Username" required>
                      </div>
                    </div>
                    <div class="form-group row">
                      <label for="password" class="col-sm-2 col-form-label">Password</label>
                      <div class="col-sm-10">
                        <input type="password" class="form-control" name="password" id="password" placeholder="Password" required>
                      </div>
                    </div>
                    <div class="form-group row">
                        <label for="package_id" class="col-sm-2 col-form-label">Jenis Paket</label>
                        <div class="col-sm-10">
                            <select class="form-control" name="package_id" id="package_id" required>
                            </select>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="team_id" class="col-sm-2 col-form-label">Sahabat</label>
                        <div class="col-sm-10">
                            <select class="form-control" name="team_id" id="team_id" required>
                            </select>
                        </div>
                    </div>
                    <!-- <div class="form-group row">
                        <label for="last_subscribe" class="col-sm-2 col-form-label">Tanggal Terakhir Berlangganan</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control datepicker" name="last_subscribe" id="last_subscribe" placeholder="Tanggal Terakhir Berlangganan" value="" required>
                        </div>
                    </div> -->
                    <div class="form-group row">
                      <div class="col-sm-12 text-right">
                          <a href="{{ route('mosque.index') }}" class="btn btn-secondary">
                              Batal
                          </a>
                          <button type="submit" class="btn btn-primary">Simpan</button>
                      </div>
                    </div>
                  </form>
              @endif
          </div><!-- /.card-body -->
        </div>
        <!-- /.nav-tabs-custom -->
      </div>
      <!-- /.col -->
    </div>
</div>

<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<script type="text/javascript">

    $(".datepicker").datepicker();

    function checkPrice(event) {
        let formatted = numeral(event.target.value).format('0,0')
        document.getElementById(event.target.id).value = formatted
    }

    searchProvince();
    searchPackage();
    searchTeam();

    function searchProvince() {
        $("#province").select2();
        $("#province").select2("destroy");
        $("#province").empty();
        axios.get('/province/select', {})
        .then(function (response) {
            let idSelect = 0;
            if ($("#province_real").val()) {
                idSelect = $("#province_real").val();
            }
            for (var i = 0; i < response.data.length; i++) {
                let selected = '';
                if (idSelect != 0) {
                    if (idSelect == response.data[i].id) {
                        selected = 'selected';
                    }
                }
                $("#province").append('<option id="province-'+response.data[i].id+'" value="'+response.data[i].id+'" '+selected+'> '+response.data[i].name+' </option>');
            }
            $("#province").select2();
        })
        .catch(function (error) {
        });
    }

    function searchPackage() {
        $("#package_id").select2();
        $("#package_id").select2("destroy");
        $("#package_id").empty();
        axios.get('/package/select', {})
        .then(function (response) {
            let idSelect = 0;
            if ($("#package_id_real").val()) {
                idSelect = $("#package_id_real").val();
            }
            for (var i = 0; i < response.data.length; i++) {
                let selected = '';
                if (idSelect != 0) {
                    if (idSelect == response.data[i].id) {
                        selected = 'selected';
                    }
                }
                $("#package_id").append('<option id="package-'+response.data[i].id+'" value="'+response.data[i].id+'" '+selected+'> '+response.data[i].name+' (Rp. '+numeral(response.data[i].price).format('0,0')+') </option>');
            }
            $("#package_id").select2();
        })
        .catch(function (error) {
        });
    }

    function searchTeam() {
        $("#team_id").select2();
        $("#team_id").select2("destroy");
        $("#team_id").empty();
        $("#team_id").append('<option id="team-0" value="0" selected> Tidak Ada </option>');
        axios.get('/team/select', {})
        .then(function (response) {
            let idSelect = 0;
            if ($("#team_id_real").val()) {
                idSelect = $("#team_id_real").val();
            }
            for (var i = 0; i < response.data.length; i++) {
                let selected = '';
                if (idSelect != 0) {
                    if (idSelect == response.data[i].id) {
                        selected = 'selected';
                    }
                }
                $("#team_id").append('<option id="team-'+response.data[i].id+'" value="'+response.data[i].id+'" '+selected+'> '+response.data[i].name+' ('+response.data[i].card_id+') </option>');
            }
            $("#team_id").select2();
        })
        .catch(function (error) {
        });
    }
</script>
@endsection

resources/views/package-form.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="card card-primary card-outline">
          <div class="card-header">
          </div><!-- /.card-header -->
          <div class="card-body">
              @if (isset($package))
                  <form method="POST" action="{{ route('package.update', $package->id) }}">
                    @csrf
                    @method('PUT')
                    <div class="form-group row">
                      <label for="name" class="col-sm-2 col-form-label">Nama Paket</label>
                      <div class="col-sm-4">
                        <input type="text" class="form-control" name="name" id="name" placeholder="Nama Paket" value="{{ $package->name }}" required>
                      </div>
                      <label for="count" class="col-sm-2 col-form-label">Jumlah Device</label>
                      <div class="col-sm-4">
                        <input type="text" class="form-control" name="count" id="count" placeholder="Jumlah Device" value="{{ $package->count }}" onkeyup="checkPrice(event)" required>
                      </div>
                    </div>
                    <div class="form-group row">
                        <label for="month" class="col-sm-2 col-form-label">Lama Bulan Langganan</label>
                        <div class="col-sm-4">
                            <input type="text" class="form-control" name="month" id="month" placeholder="Lama Bulan Langganan" value="{{ number_format($package->month, 0, '.', ',') }}" onkeyup="checkPrice(event)" required>
                        </div>
                        <label for="price" class="col-sm-2 col-form-label">Harga</label>
                        <div class="col-sm-4">
                            <input type="text" class="form-control" name="price" id="price" placeholder="Harga" value="{{ number_format($package->price, 0, '.', ',') }}" onkeyup="checkPrice(event)" required>
                        </div>
                    </div>
                    <div class="form-group row">
                      <div class="col-sm-12 text-right">
                          <a href="{{ route('package.index') }}" class="btn btn-secondary">
                              Batal
                          </a>
                          <button type="submit" class="btn btn-primary">Simpan</button>
                      </div>
                    </div>
                  </form>
              @else
                  <form method="POST" action="{{ route('package.store') }}">
                    @csrf
                    @method('POST')
                    <div class="form-group row">
                      <label for="name" class="col-sm-2 col-form-label">Nama Paket</label>
                      <div class="col-sm-4">
                        <input type="text" class="form-control" name="name" id="name" placeholder="Nama Paket" required>
                      </div>
                      <label for="count" class="col-sm-2 col-form-label">Jumlah Device</label>
                      <div class="col-sm-4">
                        <input type="text" class="form-control" name="count" id="count" placeholder="Jumlah Device" onkeyup="checkPrice(event)" required>
                      </div>
                    </div>
                    <div class="form-group row">
                        <label for="month" class="col-sm-2 col-form-label">Lama Bulan Langganan</label>
                        <div class="col-sm-4">
                            <input type="text" class="form-control" name="month" id="month" placeholder="Lama Bulan Langganan" onkeyup="checkPrice(event)" required>
                        </div>
                        <label for="price" class="col-sm-2 col-form-label">Harga</label>
                        <div class="col-sm-4">
                            <input type="text" class="form-control" name="price" id="price" placeholder="Harga" onkeyup="checkPrice(event)" required>
                        </div>
                    </div>
                    <div class="form-group row">
                      <div class="col-sm-12 text-right">
                          <a href="{{ route('package.index') }}" class="btn btn-secondary">
                              Batal
                          </a>
                          <button type="submit" class="btn btn-primary">Simpan</button>
                      </div>
                    </div>
                  </form>
              @endif
          </div><!-- /.card-body -->
        </div>
        <!-- /.nav-tabs-custom -->
      </div>
      <!-- /.col -->
    </div>
</div>

<script type="text/javascript">

    function checkPrice(event) {
        let formatted = numeral(event.target.value).format('0,0')
        document.getElementById(event.target.id).value = formatted
    }
</script>
@endsection

resources/views/team-form.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="card card-primary card-outline">
          <div class="card-header">
          </div><!-- /.card-header -->
          <div class="card-body">
              @if (isset($team))
                  <form method="POST" action="{{ route('team.update', $team->id) }}" enctype="multipart/form-data">
                    @csrf
                    @method('PUT')
                    <div class="form-group row">
                      <label for="name" class="col-sm-2 col-form-label">Nama</label>
                      <div class="col-sm-4">
                        <input type="text" class="form-control" name="name" id="name" placeholder="Nama" value="{{ $team->name }}" required>
                      </div>
                      <label for="card_id" class="col-sm-2 col-form-label">No. KTP</label>
                      <div class="col-sm-4">
                        <input type="text" class="form-control" name="card_id" id="card_id" placeholder="No. KTP" value="{{ $team->card_id }}" required>
                      </div>
                    </div>
                    <div class="form-group row">
                      <label for="born_place" class="col-sm-2 col-form-label">Tempat Lahir</label>
                      <div class="col-sm-4">
                        <input type="text" class="form-control" name="born_place" id="born_place" placeholder="Tempat Lahir" value="{{ $team->born_place }}" required>
                      </div>
                      <label for="born_date" class="col-sm-2 col-form-label">Tanggal Lahir</label>
                      <div class="col-sm-4">
                        <input type="text" class="form-control datepicker" name="born_date" id="born_date" placeholder="Tanggal Lahir" value="{{ date('m/d/Y', strtotime($team->born_date)) }}" required>
                      </div>
                    </div>
                    <div class="form-group row">
                      <label for="email" class="col-sm-2 col-form-label">Email</label>
                      <div class="col-sm-4">
                        <input type="text" class="form-control" name="email" id="email" placeholder="Email" value="{{ $team->email }}" required>
                      </div>
                      <label for="password" class="col-sm-2 col-form-label">Password</label>
                      <div class="col-sm-4">
                          <input type="password" class="form-control" name="password" id="password" placeholder="Password">
                          <small class="form-text text-muted">
                              Kosongkan jika tidak diganti.
                          </small>
                      </div>
                    </div>
                    <div class="form-group row">
                      <label for="occupation" class="col-sm-2 col-form-label">Pekerjaan</label>
                      <div class="col-sm-4">
                        <input type="text" class="form-control" name="occupation" id="occupation" placeholder="Pekerjaan" value="{{ $team->occupation }}" required>
                      </div>
                      <label for="image" class="col-sm-2 col-form-label">Foto</label>
                      <div class="col-sm-4">
                          <img src="{{ $team->image }}" class="rounded mx-auto d-block mb-2" alt="" style="width: 50%;">
                          <input type="file" class="form-control" name="image" id="image" placeholder="Foto">
                          <small class="form-text text-muted">
                              Kosongkan jika tidak diganti.
                          </small>
                      </div>
                    </div>
                    <div class="form-group row">
                        <label for="address" class="col-sm-2 col-form-label">Alamat</label>
                        <div class="col-sm-10">
                            <textarea class="form-control" name="address" id="address" rows="3" placeholder="Alamat" required>{{ $team->address }}</textarea>
                        </div>
                    </div>
                    <div class="form-group row">
                      <div class="col-sm-12 text-right">
                          <a href="{{ route('team.index') }}" class="btn btn-secondary">
                              Batal
                          </a>
                          <button type="submit" class="btn btn-primary">Simpan</button>
                      </div>
                    </div>
                  </form>
              @else
                  <form method="POST" action="{{ route('team.store') }}" enctype="multipart/form-data">
                    @csrf
                    @method('POST')
                    <div class="form-group row">
                      <label for="name" class="col-sm-2 col-form-label">Nama</label>
                      <div class="col-sm-4">
                        <input type="text" class="form-control" name="name" id="name" placeholder="Nama" required>
                      </div>
                      <label for="card_id" class="col-sm-2 col-form-label">No. KTP</label>
                      <div class="col-sm-4">
                        <input type="text" class="form-control" name="card_id" id="card_id" placeholder="No. KTP" required>
                      </div>
                    </div>
                    <div class="form-group row">
                      <label for="born_place" class="col-sm-2 col-form-label">Tempat Lahir</label>
                      <div class="col-sm-4">
                        <input type="text" class="form-control" name="born_place" id="born_place" placeholder="Tempat Lahir" required>
                      </div>
                      <label for="born_date" class="col-sm-2 col-form-label">Tanggal Lahir</label>
                      <div class="col-sm-4">
                        <input type="text" class="form-control datepicker" name="born_date" id="born_date" placeholder="Tanggal Lahir" required>
                      </div>
                    </div>
                    <div class="form-group row">
                      <label for="email" class="col-sm-2 col-form-label">Email</label>
                      <div class="col-sm-4">
                        <input type="text" class="form-control" name="email" id="email" placeholder="Email" required>
                      </div>
                      <label for="password" class="col-sm-2 col-form-label">Password</label>
                      <div class="col-sm-4">
                          <input type="password" class="form-control" name="password" id="password" placeholder="Password" required>
                      </div>
                    </div>
                    <div class="form-group row">
                      <label for="occupation" class="col-sm-2 col-form-label">Pekerjaan</label>
                      <div class="col-sm-4">
                        <input type="text" class="form-control" name="occupation" id="occupation" placeholder="Pekerjaan" required>
                      </div>
                      <label for="image" class="col-sm-2 col-form-label">Foto</label>
                      <div class="col-sm-4">
                          <input type="file" class="form-control" name="image" id="image" placeholder="Foto" required>
                      </div>
                    </div>
                    <div class="form-group row">
                        <label for="address" class="col-sm-2 col-form-label">Alamat</label>
                        <div class="col-sm-10">
                            <textarea class="form-control" name="address" id="address" rows="3" placeholder="Alamat" required></textarea>
                        </div>
                    </div>
                    <div class="form-group row">
                      <div class="col-sm-12 text-right">
                          <a href="{{ route('team.index') }}" class="btn btn-secondary">
                              Batal
                          </a>
                          <button type="submit" class="btn btn-primary">Simpan</button>
                      </div>
                    </div>
                  </form>
              @endif
          </div><!-- /.card-body -->
        </div>
        <!-- /.nav-tabs-custom -->
      </div>
      <!-- /.col -->
    </div>
</div>

<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<script type="text/javascript">

    $(".datepicker").datepicker();

</script>
@endsection